version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-local-bedrock
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DEV=True
      - ALLOWED_HOSTS=*
    volumes:
      - .:/app
      # below are negative mappings to keep from syncing large media directories
      # into the 'web' container. must come after mapping above?
      - media:/app/media
volumes:
  # these volumes are empty on purpose to clear the container's sync'ing to the
  # host
  media:
