FROM quay.io/mozmar/base:latest

# BELOW IS FROM docker/dockerfiles/bedrock_base unless otherwise noted

# Set Python-related environment variables to reduce annoying-ness
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV LANG=C.UTF-8

### from bedrock_build
ENV PATH=/node_modules/.bin:$PATH
ENV PIPELINE_LESS_BINARY=lessc
ENV PIPELINE_SASS_BINARY=node-sass
ENV PIPELINE_UGLIFYJS_BINARY=uglifyjs
ENV PIPELINE_CLEANCSS_BINARY=cleancss

RUN update-alternatives --install /bin/sh sh /bin/bash 10
RUN adduser --uid 1000 --disabled-password --gecos '' --no-create-home webdev

WORKDIR /app

EXPOSE 8000
CMD ["./bin/run.sh"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                    gettext build-essential python-{dev,pip,setuptools} \
                    libxml2-dev libxslt1.1 libxslt1-dev git libpq-dev

### from bedrock_build
RUN apt-get install -y --no-install-recommends nodejs-legacy npm

COPY ./requirements /app/requirements

# Install Python deps
### NEW: changed prod.txt to test.txt
RUN pip install --no-cache-dir -r requirements/test.txt
RUN pip install --no-cache-dir -r requirements/docker.txt

### from bedrock_build
COPY ./node_modules /
COPY ./package.json /
COPY ./lockdown.json /

# --unsafe-perm required for lockdown to function
### removed --production because we probably don't need that for local dev?
RUN cd / && npm install --unsafe-perm
