FROM node:6.10.1

ADD ./media /app/media
WORKDIR /app

RUN mkdir static

RUN npm install -g gulp-cli

COPY ./package.json package.json

RUN npm install

COPY ./gulpfile.js gulpfile.js
COPY ./.eslintrc.js .eslintrc.js
COPY ./.stylelintrc .stylelintrc
